services:
  php:
    build: 
      context: .
    restart: unless-stopped
    # env_file: .env
    volumes:
      - web:/var/www/html/
    ports:
      - "9000:9000"
    depends_on:
      db:
      condition: service_healthy

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot --password=rootpassword -e 'select 1'"] 
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/mysql

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
    volumes:
      - web:/var/www/html/
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db:
  web: