services:
  php:
    build: 
      context: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - web:/var/www/html/
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test:  ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/mysql

  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
    volumes:
      - web:/var/www/html/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      db:
        condition: service_healthy
 

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db:
  web: