hostname: ${hostname}
manage_etc_hosts: true
network:
  version: 2
  ethernets:
    ens192:
      dhcp4: false
      addresses:
        - ${ip}/${netmask}
      gateway4: ${gateway}
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
