network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - ${ip}/${netmask}
      gateway4: ${gateway}
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
