---
- name: Config Vm
  hosts: all
  become: true
  collections:
    - ansible.posix
  tasks: 
    - name: Install dependencies
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - yum-utils

    - name: Install Docker
      ansible.builtin.include_role:
        name: install_docker
    
    - name: Create User
      ansible.builtin.user:
        name: "{{ user_ipme }}"
        state: present
        group: wheel
        create_home: no

    - name: Disable root login via ssh
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Allow port 
      ansible.builtin.shell: |
        firewall-cmd --add-port={{ item }}/tcp
      loop:
        - "22"
        - "80"
        - "443"

    - name: Restart SSH service
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - sshd
        - firewalld