---
- name: Installation zabbix
  hosts: all
  become: true
  collections:
    - community.mysql.mysql_db
    - ansible.posix
  
  environment:
    DB_SERVER_HOST: {{ zabbix_db_ip }}
    ZBX_SERVER_HOST: {{ zabbix_server_ip }}
    PHP_TZ: {{ php_timezone }}

  tasks:
    - name: Install Python
      ansible.builtin.dnf:
        name: python3
        state: present

    - name: Install pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Copy dump
      ansible.builtin.copy:
        src: zabbix_dump.sql
        dest: /tmp/zabbix_dump.sql

    - name: Instalation and config database for zabbix
      ansible.builtin.include_role:
        name: database

    - name: Install rpm dependencies
      ansible.builtin.shell: |
        rpm -Uh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm

    - name: Clean Package
      ansible.builtin.command: dnf clean all

    - name: install dependencies for zabbix
      ansible.builtin.dnf:  
        name: "{{ item }}"
        state: present
      loop:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-apache-conf
        - zabbix-sql-scripts
        - zabbix-selinux-policy
        - zabbix-agent
  
    # - name: import default database schema 
    #   ansible.builtin.shell: |
    #     zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -u{{ zabbix_user_db }} -p{{ zabbix_password_db }} {{ zabbix_db }}

    - name: Simple select query
      community.mysql.mysql_query:
        login_db: "{{ zabbix_db }}"
        query: set global log_bin_trust_function_creators = 0

    - name: Copy zabbix-server config file
      ansible.builtin.template:
        src: ./templates/zabbix_server.j2
        dest: /etc/zabbix/zabbix_server.conf
        owner: {{ zabbix_user }}
        group: {{ zabbix_user_grp }}
        mode: o=rw,u=r,g=r
        force: true

    - name: Copy zabbix-agent config file
      ansible.builtin.template:
        src: ./templates/zabbix_agent.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: {{ zabbix_user }}
        group: {{ zabbix_user_grp }}
        mode: o=rw,u=r,g=r
        force: true

    - name: Copy zabbix-web config file
      ansible.builtin.template:
        src: ./templates/zabbix_php.j2
        dest: /etc/httpd/conf.d/zabbix.conf
        owner: {{ zabbix_user }}
        group: {{ zabbix_user_grp }}
        mode: o=rw,u=r,g=r
        force: true

    - name: activate communication between web interface and zabbix server
      shell: setsebool -P httpd_can_connect_zabbix on
      args:
        warn: no

    - name: permit web interface to connect into database server
      shell: setsebool -P httpd_can_network_connect_db on
      args:
        warn: no

    - name: Restart services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - zabbix-server
        - zabbix-agent
        - httpd
        - php-fpm

    ##### DELETE THIS JOB, THE PORT 80 WILL BE OPEN ####
    - name: Allow port 
      ansible.builtin.shell: firewall-cmd --add-port={{ item }}/tcp
      loop:
        - "80"